# Generated by Django 4.0.4 on 2022-04-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationForm',
            new_name='landing_pageRegistrationForm',
        ),
    ]
