# Generated by Django 4.0.4 on 2022-04-18 17:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_registrationform_landing_pageregistrationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_pageregistrationform',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=10, region=None),
        ),
        migrations.AlterField(
            model_name='landing_pageregistrationform',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='landing_pageregistrationform',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
