# Generated by Django 4.0.4 on 2022-04-18 17:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_landing_pageregistrationform_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing_pageregistrationform',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
