# Generated by Django 4.0.4 on 2022-04-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_landing_pageregistrationform_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing_pageregistrationform',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
